apiVersion: v1
kind: Service
metadata:
  name: messages
  labels:
    app: messages
spec:
  type: ClusterIP
  selector:
    app: messages
  ports:
    - name: http
      port: 8084
      targetPort: 8084
