apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/postgres
  - ../../../k8s/base/auth
  - ../../../k8s/base/keys
  - ../../../k8s/base/messages
  - ../../../k8s/base/gateway
