apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/keys
configMapGenerator:
  - name: keys-config
    literals:
      - ADDR=:8082
secretGenerator:
generatorOptions:
  disableNameSuffixHash: true
