apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  # ensure this matches your app namespace (or let Argo fill it via kustomize/overlays)
  # namespace: default
  annotations:
    # make sure this is created before jobs (optional but nice)
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  POSTGRES_USER: secumsg
  POSTGRES_PASSWORD: supersecretpassword
  POSTGRES_DB_AUTH: auth_db
  POSTGRES_DB_KEYS: keys_db
  POSTGRES_DB_MESSAGES: messages_db
