apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/messages
configMapGenerator:
  - name: messages-config
    literals:
      - MESSAGES_ADDR=:8084
secretGenerator:
  - name: messages-secret
    literals:
      - MESSAGES_DATABASE_URL=postgres://app:secret@postgres:5432/messagesdb?sslmode=disable
generatorOptions:
  disableNameSuffixHash: true
