apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/messages
configMapGenerator:
  - name: messages-config
    literals:
      - MESSAGES_ADDR=:8084
secretGenerator:
generatorOptions:
  disableNameSuffixHash: true
