apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-configmap.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - loki-configmap.yaml
  - loki-pvc.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - promtail-configmap.yaml
  - promtail-rbac.yaml
  - promtail-daemonset.yaml
  - grafana-provisioning-configmap.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-pvc.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
