apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../infra/k8s/base/postgres
  - ../../../infra/k8s/base/observability
  - ../minikube-auth
  - ../minikube-keys
  - ../minikube-messages
  - ../minikube-gateway
