name: Lint Services

on:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - services/auth
          - services/gateway
          - services/crypto-core
          - services/keys
          - services/messages

    steps:
      - uses: actions/checkout@v4

      - name: Show module
        run: ls -la ${{ matrix.module }}

      - name: Lint ${{ matrix.module }}
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            -w /repo/${{ matrix.module }} \
            golangci/golangci-lint:latest \
            golangci-lint run --timeout=5m
