# .github/workflows/lint.yml
name: Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - services/auth
          - services/gateway
          - services/crypto-core
          - services/keys

    steps:
      - uses: actions/checkout@v4

      - name: Show module
        run: ls -la ${{ matrix.module }}

      - name: Lint ${{ matrix.module }}
        run: |
          docker run --rm \
            -v "$PWD/${{ matrix.module }}":/app \
            -w /app \
            golangci/golangci-lint:latest \
            golangci-lint run --timeout=5m
